// stages.js — the eight worlds: terrain shape, physics flavour and palette.
//
// Everything here is data plus a couple of pure helpers. A world is described
// by the parameters its terrain generator consumes (hill amplitude, hill
// wavelength, roughness), the physics it bends (gravity, grip, air drag) and a
// theme the renderer paints from. Each world is both a set of six campaign
// levels (levels.js) and an endless stage.

export const STORE_PREFIX = "hillclimb:";
export const storeKey = (name) => STORE_PREFIX + name;

// Theme fields the renderer reads:
//   sky0/sky1/horizon  top, lower sky and the glow sitting on the horizon
//   sun, sunKind       "sun" | "moon" | "earth" — and its colour
//   stars              draw a starfield
//   ridges             three far-to-near silhouette colours
//   caps               snow caps on the far ridge (colour) or null
//   skyline            a city silhouette on the middle ridge
//   crust/crustHi      surface band and its lit edge
//   soil/soilDark      top and bottom of the ground body
//   strata             colour of the bands through the ground
//   stone              embedded rocks
//   grass              tufts along the surface, or null
//   surface            extra surface detail: "road" | "snow" | "cracks" | "craters" | null
//   deco               scenery kinds scattered along the road
//   clouds             false for a world with no atmosphere
//   weather            "snow" | "dust" | "embers" | "fireflies" | "rain" | "leaves" | null
//   hazard             pit fill: { kind, top, deep, glow }
//   lights             night world: headlights on, lamps glow

export const STAGES = [
  {
    id: "countryside",
    name: "Countryside",
    blurb: "Rolling green hills. Gentle enough to learn the throttle on.",
    unlockAt: 0,
    gravity: 15,
    grip: 1,
    drag: 0.014,
    terrain: { amp: 3.4, wave: 19, rough: 0.8, bumps: 0.7, ramp: 0.8 },
    theme: {
      sky0: "#4aa8f0",
      sky1: "#bfe6ff",
      horizon: "#fff4d6",
      sun: "#fff3c4",
      sunKind: "sun",
      stars: false,
      ridges: ["#a9cfe0", "#7fb894", "#5a9c6c"],
      caps: null,
      skyline: false,
      crust: "#5cc86a",
      crustHi: "#9dea7c",
      soil: "#6b4a2e",
      soilDark: "#3a2818",
      strata: "#7d5936",
      stone: "#8c7a66",
      grass: "#3fae55",
      surface: null,
      accent: "#3ddc84",
      cloud: "#ffffff",
      deco: ["tree", "tree", "bush", "fence"],
      weather: "leaves",
      hazard: { kind: "water", top: "#5ec8ff", deep: "#1c5fa8", glow: null },
      lights: false,
    },
  },
  {
    id: "desert",
    name: "Desert",
    blurb: "Long dunes and loose sand. Momentum is everything out here.",
    unlockAt: 600,
    gravity: 15,
    grip: 0.86,
    drag: 0.013,
    terrain: { amp: 4.4, wave: 26, rough: 0.85, bumps: 0.5, ramp: 0.95 },
    theme: {
      sky0: "#f08a4b",
      sky1: "#ffd9a0",
      horizon: "#fff0c0",
      sun: "#fff0b8",
      sunKind: "sun",
      stars: false,
      ridges: ["#e9c29a", "#dba272", "#c98552"],
      caps: null,
      skyline: false,
      crust: "#f2cd8a",
      crustHi: "#fff0c2",
      soil: "#b57e4f",
      soilDark: "#6e4526",
      strata: "#c89464",
      stone: "#9c6a44",
      grass: null,
      surface: null,
      accent: "#ffb020",
      cloud: "#fff2dc",
      deco: ["cactus", "cactus", "rock", "skull"],
      weather: "dust",
      hazard: { kind: "water", top: "#4fd8d0", deep: "#127a8a", glow: null },
      lights: false,
    },
  },
  {
    id: "forest",
    name: "Forest",
    blurb: "Dusk under the pines. Bumpy trails and swampy hollows.",
    unlockAt: 1000,
    gravity: 15,
    grip: 0.95,
    drag: 0.014,
    terrain: { amp: 3.8, wave: 16, rough: 1.05, bumps: 1, ramp: 0.85 },
    theme: {
      sky0: "#3b2a5c",
      sky1: "#f08a6a",
      horizon: "#ffc98a",
      sun: "#ffd29a",
      sunKind: "sun",
      stars: true,
      ridges: ["#6a4a6e", "#3f3552", "#253040"],
      caps: null,
      skyline: false,
      crust: "#4f8f3e",
      crustHi: "#8fc45a",
      soil: "#4a3424",
      soilDark: "#221710",
      strata: "#5c4230",
      stone: "#6b6259",
      grass: "#3b7a33",
      surface: null,
      accent: "#ffcf5a",
      cloud: "#f7b8a0",
      deco: ["fir", "fir", "mushroom", "stump"],
      weather: "fireflies",
      hazard: { kind: "swamp", top: "#7fae3c", deep: "#2c4a1c", glow: null },
      lights: true,
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    blurb: "Ice with almost no grip. Feather the gas or spin the wheels.",
    unlockAt: 1600,
    gravity: 15,
    grip: 0.62,
    drag: 0.012,
    terrain: { amp: 4.1, wave: 18, rough: 1, bumps: 0.9, ramp: 0.85 },
    theme: {
      sky0: "#2d5d8e",
      sky1: "#bfe2f5",
      horizon: "#f2fbff",
      sun: "#eaf6ff",
      sunKind: "sun",
      stars: false,
      ridges: ["#c4dcec", "#94b8d2", "#7196b6"],
      caps: "#ffffff",
      skyline: false,
      crust: "#f2faff",
      crustHi: "#ffffff",
      soil: "#8fb0c8",
      soilDark: "#48657f",
      strata: "#a9c6da",
      stone: "#6f8ca3",
      grass: null,
      surface: "snow",
      accent: "#67e8f9",
      cloud: "#ffffff",
      deco: ["pine", "pine", "snowman", "ice"],
      weather: "snow",
      hazard: { kind: "icewater", top: "#8fd6ff", deep: "#0f3a66", glow: null },
      lights: false,
    },
  },
  {
    id: "highway",
    name: "Highway",
    blurb: "Smooth tarmac, big grip, bigger speed. Mind the crests.",
    unlockAt: 3200,
    gravity: 15,
    grip: 1.15,
    drag: 0.011,
    terrain: { amp: 3.8, wave: 30, rough: 0.45, bumps: 0.3, ramp: 1 },
    theme: {
      sky0: "#0c1024",
      sky1: "#3a3f78",
      horizon: "#ff7aa8",
      sun: "#ffe3b0",
      sunKind: "moon",
      stars: true,
      ridges: ["#2a2d58", "#1c1e3e", "#14152c"],
      caps: null,
      skyline: true,
      crust: "#3a3f4b",
      crustHi: "#6b7285",
      soil: "#2b2f38",
      soilDark: "#12141a",
      strata: "#353a45",
      stone: "#4a505e",
      grass: null,
      surface: "road",
      accent: "#ff5d8f",
      cloud: "#6a6f9e",
      deco: ["lamp", "lamp", "cone", "sign"],
      weather: "rain",
      hazard: { kind: "spikes", top: "#ff5d8f", deep: "#0a0b12", glow: "#ff5d8f" },
      lights: true,
    },
  },
  {
    id: "canyon",
    name: "Canyon",
    blurb: "Red rock, deep gorges and big air off the mesas.",
    unlockAt: 4000,
    gravity: 15,
    grip: 1.02,
    drag: 0.013,
    terrain: { amp: 4.9, wave: 22, rough: 0.9, bumps: 0.6, ramp: 1 },
    theme: {
      sky0: "#e0664a",
      sky1: "#ffc28a",
      horizon: "#ffe6b8",
      sun: "#fff0c8",
      sunKind: "sun",
      stars: false,
      ridges: ["#e3a27e", "#c66a48", "#9a4a32"],
      caps: null,
      skyline: false,
      crust: "#d9794a",
      crustHi: "#f4a672",
      soil: "#a4502f",
      soilDark: "#4e2415",
      strata: "#c0663e",
      stone: "#7a3a24",
      grass: null,
      surface: null,
      accent: "#ff8a4c",
      cloud: "#ffe0c8",
      deco: ["mesa", "deadtree", "rock", "mesa"],
      weather: "dust",
      hazard: { kind: "water", top: "#5fd0c0", deep: "#1a5a6a", glow: null },
      lights: false,
    },
  },
  {
    id: "volcano",
    name: "Volcano",
    blurb: "Ash, obsidian and rivers of lava. Don't dip a wheel.",
    unlockAt: 4600,
    gravity: 15,
    grip: 0.98,
    drag: 0.013,
    terrain: { amp: 4.6, wave: 17, rough: 1, bumps: 0.8, ramp: 1 },
    theme: {
      sky0: "#16080a",
      sky1: "#6a1f16",
      horizon: "#ff7a2a",
      sun: "#ffb070",
      sunKind: "none",
      stars: false,
      ridges: ["#4a1c18", "#2e1412", "#1c0d0c"],
      caps: null,
      skyline: false,
      crust: "#3a3334",
      crustHi: "#6a5c5a",
      soil: "#2a2224",
      soilDark: "#0e0a0b",
      strata: "#3a2a2a",
      stone: "#1a1415",
      grass: null,
      surface: "cracks",
      accent: "#ff6a2a",
      cloud: "#4a3a3a",
      deco: ["charred", "lavarock", "charred", "vent"],
      weather: "embers",
      hazard: { kind: "lava", top: "#ffb02a", deep: "#d0280e", glow: "#ff6a1a" },
      lights: true,
    },
  },
  {
    id: "moon",
    name: "Moon",
    blurb: "One-sixth gravity, dusty craters. Every jump is a long one.",
    unlockAt: 5200,
    gravity: 5.4,
    grip: 0.7,
    drag: 0.003,
    terrain: { amp: 4.5, wave: 24, rough: 0.9, bumps: 0.7, ramp: 0.9 },
    theme: {
      sky0: "#02030a",
      sky1: "#101430",
      horizon: "#2a3060",
      sun: "#dfe7ff",
      sunKind: "earth",
      stars: true,
      ridges: ["#2d3350", "#3c4262", "#50567a"],
      caps: null,
      skyline: false,
      crust: "#c4c8d8",
      crustHi: "#eef0f8",
      soil: "#6c7186",
      soilDark: "#2a2e3e",
      strata: "#7c8198",
      stone: "#4a4f62",
      grass: null,
      surface: "craters",
      accent: "#a06bff",
      cloud: "#6a70a0",
      clouds: false,
      deco: ["rock", "rock", "antenna", "flag"],
      weather: null,
      hazard: { kind: "void", top: "#a06bff", deep: "#000000", glow: "#a06bff" },
      lights: true,
    },
  },
];

export const getStage = (id) => STAGES.find((s) => s.id === id) || STAGES[0];
